# These are supported funding model platforms

github: hab ich nicht # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: hab ich nicht # Replace with a single Patreon username
open_collective: hab ich nicht # Replace with a single Open Collective username
ko_fi: hab ich nicht # Replace with a single Ko-fi username
tidelift: hab ich nicht # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: hab ich nicht # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: hab ich nicht # Replace with a single Liberapay username
issuehunt: hab ich nicht # Replace with a single IssueHunt username
lfx_crowdfunding: hab ich nicht # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: hab ich nicht # Replace with a single Polar username
buy_me_a_coffee: hab ich nicht # Replace with a single Buy Me a Coffee username
thanks_dev: hab ich nicht # Replace with a single thanks.dev username
custom: hab ich nicht # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
